import type { ITheme } from "@xterm/xterm";
import type { TerminalThemeName } from "../store/appSettings";

// Keep theme palettes in one place so Settings and terminal stay in sync.
export const TERMINAL_THEME_OPTIONS: Array<{
  value: TerminalThemeName;
  label: string;
}> = [
  { value: "light", label: "Light" },
  { value: "dark", label: "Dark" },
  { value: "monokai", label: "Monokai" },
  { value: "solarized", label: "Solarized" },
  { value: "nord", label: "Nord" },
  { value: "dracula", label: "Dracula" },
  { value: "gruvbox", label: "Gruvbox" },
  { value: "tokyo", label: "Tokyo" },
  { value: "catppuccin", label: "Catppuccin" },
];

export function getXtermTheme(name: TerminalThemeName): ITheme {
  switch (name) {
    case "dark":
      return {
        background: "#0f111a",
        foreground: "#d6deeb",
        cursor: "#ffd166",
        cursorAccent: "#0f111a",
        selectionBackground: "rgba(255, 209, 102, 0.25)",
        black: "#1f2330",
        red: "#ff5c57",
        green: "#4cc38a",
        yellow: "#ffd166",
        blue: "#5cc8ff",
        magenta: "#c792ea",
        cyan: "#5fdbff",
        white: "#d6deeb",
        brightBlack: "#3a3f4b",
        brightRed: "#ff7b72",
        brightGreen: "#6ee7b7",
        brightYellow: "#ffe08a",
        brightBlue: "#7dd3fc",
        brightMagenta: "#e9d5ff",
        brightCyan: "#99f6e4",
        brightWhite: "#ffffff",
      };
    case "monokai":
      return {
        background: "#272822",
        foreground: "#f8f8f2",
        cursor: "#ffd866",
        cursorAccent: "#272822",
        selectionBackground: "rgba(248, 248, 242, 0.18)",
        black: "#272822",
        red: "#ff6188",
        green: "#a9dc76",
        yellow: "#ffd866",
        blue: "#78dce8",
        magenta: "#ab9df2",
        cyan: "#78dce8",
        white: "#f8f8f2",
        brightBlack: "#75715e",
        brightRed: "#ff6188",
        brightGreen: "#a9dc76",
        brightYellow: "#ffd866",
        brightBlue: "#78dce8",
        brightMagenta: "#ab9df2",
        brightCyan: "#78dce8",
        brightWhite: "#ffffff",
      };
    case "solarized":
      // Solarized Dark
      return {
        background: "#002b36",
        foreground: "#93a1a1",
        cursor: "#b58900",
        cursorAccent: "#002b36",
        selectionBackground: "rgba(147, 161, 161, 0.22)",
        black: "#073642",
        red: "#dc322f",
        green: "#859900",
        yellow: "#b58900",
        blue: "#268bd2",
        magenta: "#d33682",
        cyan: "#2aa198",
        white: "#eee8d5",
        brightBlack: "#586e75",
        brightRed: "#cb4b16",
        brightGreen: "#586e75",
        brightYellow: "#657b83",
        brightBlue: "#839496",
        brightMagenta: "#6c71c4",
        brightCyan: "#93a1a1",
        brightWhite: "#fdf6e3",
      };
    case "nord":
      return {
        background: "#2e3440",
        foreground: "#d8dee9",
        cursor: "#88c0d0",
        cursorAccent: "#2e3440",
        selectionBackground: "rgba(136, 192, 208, 0.25)",
        black: "#3b4252",
        red: "#bf616a",
        green: "#a3be8c",
        yellow: "#ebcb8b",
        blue: "#81a1c1",
        magenta: "#b48ead",
        cyan: "#88c0d0",
        white: "#e5e9f0",
        brightBlack: "#4c566a",
        brightRed: "#bf616a",
        brightGreen: "#a3be8c",
        brightYellow: "#ebcb8b",
        brightBlue: "#81a1c1",
        brightMagenta: "#b48ead",
        brightCyan: "#8fbcbb",
        brightWhite: "#eceff4",
      };
    case "dracula":
      return {
        background: "#282a36",
        foreground: "#f8f8f2",
        cursor: "#ffb86c",
        cursorAccent: "#282a36",
        selectionBackground: "rgba(248, 248, 242, 0.2)",
        black: "#21222c",
        red: "#ff5555",
        green: "#50fa7b",
        yellow: "#f1fa8c",
        blue: "#8be9fd",
        magenta: "#bd93f9",
        cyan: "#8be9fd",
        white: "#f8f8f2",
        brightBlack: "#6272a4",
        brightRed: "#ff6e6e",
        brightGreen: "#69ff94",
        brightYellow: "#ffffa5",
        brightBlue: "#a4ffff",
        brightMagenta: "#d6acff",
        brightCyan: "#a4ffff",
        brightWhite: "#ffffff",
      };
    case "gruvbox":
      return {
        background: "#282828",
        foreground: "#ebdbb2",
        cursor: "#fabd2f",
        cursorAccent: "#282828",
        selectionBackground: "rgba(250, 189, 47, 0.2)",
        black: "#1d2021",
        red: "#fb4934",
        green: "#b8bb26",
        yellow: "#fabd2f",
        blue: "#83a598",
        magenta: "#d3869b",
        cyan: "#8ec07c",
        white: "#ebdbb2",
        brightBlack: "#665c54",
        brightRed: "#fe8019",
        brightGreen: "#b8bb26",
        brightYellow: "#fabd2f",
        brightBlue: "#83a598",
        brightMagenta: "#d3869b",
        brightCyan: "#8ec07c",
        brightWhite: "#fbf1c7",
      };
    case "tokyo":
      return {
        background: "#1a1b26",
        foreground: "#c0caf5",
        cursor: "#7aa2f7",
        cursorAccent: "#1a1b26",
        selectionBackground: "rgba(122, 162, 247, 0.22)",
        black: "#15161e",
        red: "#f7768e",
        green: "#9ece6a",
        yellow: "#e0af68",
        blue: "#7aa2f7",
        magenta: "#bb9af7",
        cyan: "#7dcfff",
        white: "#a9b1d6",
        brightBlack: "#414868",
        brightRed: "#f7768e",
        brightGreen: "#9ece6a",
        brightYellow: "#e0af68",
        brightBlue: "#7aa2f7",
        brightMagenta: "#bb9af7",
        brightCyan: "#7dcfff",
        brightWhite: "#c0caf5",
      };
    case "catppuccin":
      return {
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        cursor: "#f5c2e7",
        cursorAccent: "#1e1e2e",
        selectionBackground: "rgba(245, 194, 231, 0.22)",
        black: "#181825",
        red: "#f38ba8",
        green: "#a6e3a1",
        yellow: "#f9e2af",
        blue: "#89b4fa",
        magenta: "#f5c2e7",
        cyan: "#94e2d5",
        white: "#cdd6f4",
        brightBlack: "#45475a",
        brightRed: "#f38ba8",
        brightGreen: "#a6e3a1",
        brightYellow: "#f9e2af",
        brightBlue: "#89b4fa",
        brightMagenta: "#f5c2e7",
        brightCyan: "#94e2d5",
        brightWhite: "#f5e0dc",
      };
    case "light":
    default:
      // Friendly light theme aligned with app tokens.
      return {
        background: "#f1f2f5",
        foreground: "#2c2c2c",
        cursor: "#0f8fff",
        cursorAccent: "#ffffff",
        selectionBackground: "rgba(15, 143, 255, 0.18)",
        black: "#2c2c2c",
        red: "#e51400",
        green: "#16825d",
        yellow: "#ca5010",
        blue: "#0f8fff",
        magenta: "#881798",
        cyan: "#3a96dd",
        white: "#e5e5e5",
        brightBlack: "#6b6b6b",
        brightRed: "#ff6347",
        brightGreen: "#4ec9b0",
        brightYellow: "#f9a825",
        brightBlue: "#3b8eea",
        brightMagenta: "#d670d6",
        brightCyan: "#29b8db",
        brightWhite: "#f5f5f5",
      };
  }
}

